### ISSUE TITLE
설정?

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-android#11]
설정 화면이 필요할까요?

**Comment by dobbi030** [comment]
설정화면에 원래 무엇을 넣기로 했었죠?

**Comment by dobbi030** [comment]
기기 변경이나 사용자 로그인 기능이 들어간다면 로그인 뭐 그런거 넣으면 되지 않을까요?

**Comment by potados99** [comment]
원래 기기 관련 설정이나 계정 설정을 넣기로 했던 것으로 기억해요. 구현하고 보니 딱히 기기 관련해서 설정할 것이 없네요. 로그인 도입되면 해당 부분 넣으면 될 것 같습니다.
