### ISSUE TITLE
신발? 기기?

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-android#13]
어떤 단어를 사용하는 것이 나을까요?

**Comment by dobbi030** [comment]
어플 내에서 말씀이신가요?
신발에 구애받지 않고 기기만 변경해서 사용할 수 있다는 점을 살려서 기기라고 하는게 어떨까요?

**Comment by potados99** [comment]
의견 감사합니다. #14 PR에서 반영하였습니다.
